clc;
clear;
close all;
fc = 28e9;
c = physconst('LightSpeed');
lambda = c/fc;

N = 8;

array = phased.ULA( ...
    'NumElements',N,...
    'ElementSpacing',lambda/2);

sv = phased.SteeringVector( ...
    'SensorArray',array,...
    'PropagationSpeed',c);

weights = sv(fc,30);

saveFolder = fullfile('..','Figures','05_3DRadiation');

if ~exist(saveFolder,'dir')
    mkdir(saveFolder)
end

figure;

pattern(array,...
    fc,...
    -180:180,...
    -90:90,...
    'CoordinateSystem','polar',...
    'Type','directivity',...
    'Weights',weights,...
    'PropagationSpeed',c);

title('3D Radiation Pattern (30° Beam Steering)');

exportgraphics(gcf,...
    fullfile(saveFolder,'3DRadiation_30deg.png'),...
    'Resolution',300);