clc;
clear;
close all;

%% =====================================================
% SMART ANTENNA DASHBOARD (Professional Version)
% Beam Steering Smart Antenna for 6G
%% =====================================================

f = figure(...
    'Name','6G Smart Antenna Control Dashboard',...
    'NumberTitle','off',...
    'Color',[0.08 0.08 0.08],...
    'Position',[80 40 1500 850]);

%% ===========================
% Dashboard Title
%% ===========================

annotation('textbox',...
    [0.02 0.94 0.96 0.05],...
    'String','6G SMART ANTENNA BEAM TRACKING DASHBOARD',...
    'FontSize',20,...
    'FontWeight','bold',...
    'Color','white',...
    'EdgeColor','none',...
    'HorizontalAlignment','center');
%% =====================================================
% System Parameters
%% =====================================================

fc = 28e9;
c = physconst('LightSpeed');
lambda = c/fc;

N = 8;

d = lambda/2;

theta = -90:0.2:90;

trackingRadius = 1;

beamWidth = 16;

saveFolder = fullfile('..','Figures','16_UserTrackingAnimation');

if ~exist(saveFolder,'dir')
    mkdir(saveFolder);
end

gifFile = fullfile(saveFolder,'BeamTracking.gif');
%% =====================================================
% Animation Loop
%% =====================================================

for frame = 1:61

    userAngle = -60 + (frame-1)*2;

    clf(f);

    %% =====================================================
    % Dashboard Title
    %% =====================================================

    annotation('textbox',...
        [0.02 0.94 0.96 0.05],...
        'String','6G SMART ANTENNA BEAM TRACKING DASHBOARD',...
        'HorizontalAlignment','center',...
        'FontSize',20,...
        'FontWeight','bold',...
        'EdgeColor','none',...
        'Color','white');

    %% =====================================================
    % LEFT PANEL
    %% =====================================================

    ax1 = subplot(2,2,[1 3]);

    set(ax1,...
        'Color',[0.12 0.12 0.12],...
        'XColor','w',...
        'YColor','w');

    hold on
    grid on
    axis equal

    xlim([-1.3 1.3])
    ylim([-1.3 1.3])

    title('Tracking Environment','Color','w')

    xlabel('X Position','Color','w')
    ylabel('Y Position','Color','w')

    %% Coverage Circle

    th = linspace(0,2*pi,400);

    fill(1.05*cos(th),...
         1.05*sin(th),...
         [0.15 0.22 0.40],...
         'FaceAlpha',0.30,...
         'EdgeColor',[0.4 0.8 1],...
         'LineWidth',1.2);

    %% Base Station

    plot(0,0,...
        'bs',...
        'MarkerFaceColor','c',...
        'MarkerSize',18);

    text(0,-0.15,...
        'Base Station',...
        'Color','w',...
        'FontWeight','bold',...
        'HorizontalAlignment','center');

    %% User Position

    x = trackingRadius*cosd(userAngle);
    y = trackingRadius*sind(userAngle);
    if ~exist('pathX','var')
        pathX = [];
        pathY = [];
    end

    pathX(end+1) = x;
    pathY(end+1) = y;
    %% Beam Sector

    sector = linspace(userAngle-beamWidth,...
                      userAngle+beamWidth,...
                      60);

    bx = [0 trackingRadius*cosd(sector) 0];
    by = [0 trackingRadius*sind(sector) 0];

    fill(bx,...
         by,...
         [0 1 0],...
         'FaceAlpha',0.18,...
         'EdgeColor','none');

    %% Beam Centre

   plot([0 x],[0 y],...
    'Color',[0 1 0],...
    'LineWidth',3.5);

    %% User

   plot(x,y,...
    'ro',...
    'MarkerFaceColor','r',...
    'MarkerEdgeColor','w',...
    'LineWidth',2,...
    'MarkerSize',11);
   text(x,...
     y+0.08,...
     sprintf('User : %.0f°',userAngle),...
     'Color','yellow',...
     'FontWeight','bold',...
     'HorizontalAlignment','center');
    %% =====================================================
    % RIGHT PANEL
    %% =====================================================

    subplot(2,2,2)

    AF = zeros(size(theta));

    for k = 1:length(theta)

        psi = 2*pi*d/lambda * ...
             (sind(theta(k))-sind(userAngle));

        AF(k)=abs(sum(exp(1j*(0:N-1)*psi)));

    end

    AF = AF/max(AF);

    AFdB = 20*log10(AF);

    AFdB(AFdB<-40)=-40;

    plot(theta,...
         AFdB,...
         'c',...
         'LineWidth',2.5);

    hold on

    xline(userAngle,...
        '--r',...
        'LineWidth',1.5);

    plot(userAngle,...
         0,...
         'ro',...
         'MarkerFaceColor','r');
    legend({'Beam Pattern','Estimated User'},...
        'TextColor','w',...
        'Location','northeast');

    grid on
    box on
    set(gca,'GridAlpha',0.35)

    set(gca,...
        'Color',[0.12 0.12 0.12],...
        'XColor','w',...
        'YColor','w');

    title('Adaptive Beam Pattern','Color','w')

    xlabel('Angle (Degrees)','Color','w')

    ylabel('Normalized Gain (dB)','Color','w')

    xlim([-90 90])

    ylim([-40 2])

    %% =====================================================
    % TELEMETRY
    %% =====================================================

    subplot(2,2,4)

    axis off

    text(0.02,0.92,...
        'LIVE TELEMETRY',...
        'Color','cyan',...
        'FontSize',16,...
        'FontWeight','bold');

    text(0.02,0.78,...
        sprintf('Frequency : %.0f GHz',fc/1e9),...
        'Color','w',...
        'FontSize',13);

    text(0.02,0.68,...
        sprintf('Elements : %d',N),...
        'Color','w',...
        'FontSize',13);

    text(0.02,0.58,...
        sprintf('User Angle : %.0f°',userAngle),...
        'Color','w',...
        'FontSize',13);

    text(0.02,0.48,...
        sprintf('Estimated DOA : %.0f°',userAngle),...
        'Color','w',...
        'FontSize',13);

    text(0.02,0.38,...
        sprintf('Beam Direction : %.0f°',userAngle),...
        'Color','w',...
        'FontSize',13);

    beamGain = 10*log10(N)+6;
    trackingError = 0;

    RSSI = -40 + beamGain;

    SNR = 20 + beamGain/2;

    text(0.02,0.28,...
        sprintf('Beam Gain : %.2f dBi',beamGain),...
        'Color','w',...
        'FontSize',13);
    text(0.02,0.16,...
        sprintf('RSSI : %.1f dBm',RSSI),...
        'Color','w',...
        'FontSize',13);

    text(0.02,0.08,...
        sprintf('SNR : %.1f dB',SNR),...
        'Color','w',...
        'FontSize',13);

    text(0.55,0.78,...
        sprintf('Tracking Error : %.1f°',trackingError),...
        'Color','yellow',...
        'FontSize',13);

    text(0.02,0.00,...
        'Tracking Status : LOCKED',...
        'Color',[0 1 0],...
        'FontSize',13,...
        'FontWeight','bold');

    text(0.02,-0.08,...
        sprintf('Frame : %d / 61',frame),...
        'Color','yellow',...
        'FontSize',13);

    drawnow

    %% GIF

    frameImage = getframe(f);

    img = frame2im(frameImage);

    [A,map] = rgb2ind(img,256);

    if frame==1

        imwrite(A,map,...
            gifFile,...
            'gif',...
            'LoopCount',Inf,...
            'DelayTime',0.07);

    else

        imwrite(A,map,...
            gifFile,...
            'gif',...
            'WriteMode','append',...
            'DelayTime',0.07);

    end

end
%% Save Final Dashboard

set(gcf,'InvertHardcopy','off');

exportgraphics(...
    gcf,...
    fullfile(saveFolder,'SmartTrackingDashboard.png'),...
    'Resolution',300,...
    'BackgroundColor','current');


disp('===========================================')
disp('Smart Tracking Dashboard Completed')
disp('GIF Saved Successfully')
disp('===========================================')