clc;
close all;

%% Parameters

fc = 28e9;
N = 8;

beamGain = 15.03;
beamwidth = 12.7;

%% Create Figure

figure(...
    'Color',[0.08 0.08 0.08],...
    'Position',[250 120 900 600]);

for k = 1:60

    clf

    set(gcf,'Color',[0.08 0.08 0.08])

    %% Simulated Live Parameters

    userAngle = -60 + 2*k;

    estimatedDOA = userAngle + randn*0.15;

    trackingError = abs(userAngle-estimatedDOA);

    RSSI = -25 + randn*0.5;

    SNR = 28 + randn;

    latency = 0.8 + rand*0.3;

    throughput = 10 + rand*2;

    trackingStatus = "LOCKED";

    %% Dashboard

    axis off

    text(0.02,0.93,...
        'SYSTEM PERFORMANCE MONITOR',...
        'Color','cyan',...
        'FontSize',24,...
        'FontWeight','bold');

    text(0.02,0.82,...
        sprintf('Carrier Frequency : %.0f GHz',fc/1e9),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.76,...
        sprintf('Array Elements : %d',N),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.70,...
        sprintf('User Angle : %.1f°',userAngle),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.64,...
        sprintf('Estimated DOA : %.1f°',estimatedDOA),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.58,...
        sprintf('Tracking Error : %.2f°',trackingError),...
        'Color','yellow',...
        'FontSize',16);

    text(0.02,0.52,...
        sprintf('Beam Gain : %.2f dBi',beamGain),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.46,...
        sprintf('Beamwidth : %.2f°',beamwidth),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.40,...
        sprintf('RSSI : %.2f dBm',RSSI),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.34,...
        sprintf('SNR : %.2f dB',SNR),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.28,...
        sprintf('Latency : %.2f ms',latency),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.22,...
        sprintf('Throughput : %.2f Gbps',throughput),...
        'Color','w',...
        'FontSize',16);

    text(0.02,0.16,...
        sprintf('Tracking Status : %s',trackingStatus),...
        'Color','green',...
        'FontSize',18,...
        'FontWeight','bold');

    drawnow

    pause(0.05)

end

disp('=====================================')
disp('System Performance Monitor Completed')
disp('=====================================')